app/routes/entidad_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.services import entidad_service
import mysql.connector.errors
from io import BytesIO
import base64

bp_entidad = Blueprint('entidad', __name__)
error = mysql.connector.errors

#Ruta ventana Datos de entidad
@bp_entidad.get('/entidad')
def entidad():
    try:
        ent = entidad_service.listar_entidad_arr()
        return render_template('temp_entidad/entidad.html', ent = ent)

    except error.Error as e:
        flash(f"Se presentó un error inesperado: {e.msg}","error")
        return redirect(url_for('entidad.entidad'))
    
    except Exception as ex:
        flash(f"Se presentó un error inesperado: {ex}","error")
        return redirect(url_for('entidad.entidad'))
    
#Ruta ventana agregar datos en entidad
@bp_entidad.get('/add_entidad')
def add_entidad():
    try:
        return render_template('temp_entidad/add_entidad.html')

    except error.Error as e:
        flash(f"Se presentó un error inesperado: {e.msg}","error")
        return redirect(url_for('entidad.entidad'))
    
    except Exception as ex:
        flash(f"Se presentó un error inesperado: {ex}","error")
        return redirect(url_for('entidad.entidad'))
    
#Ruta POST para insertar datos de entidad en base de datos
@bp_entidad.post('/f_addEntidad')
def f_addEntidad():
    try:
        nit_entidad = request.form["nit_entidad"]
        digito_nit = request.form["digito_nit"]
        nom_entidad = request.form["nom_entidad"]
        dir_entidad = request.form["dir_entidad"]
        tel_entidad = request.form["tel_entidad"]
        correo_entidad = request.form["correo_entidad"]
        pais_entidad = request.form["pais_entidad"]
        depto_entidad = request.form["depto_entidad"]
        mun_entidad = request.form["mun_entidad"]
        cod_habilitacion = request.form["cod_habilitacion"]
        gerente = request.form["gerente"]
        revisor = request.form["revisor"]
        resolucion_dian = request.form["resolucion_dian"]
        logo_entidad = request.files["logo_entidad"]
        if logo_entidad:
            img_data = logo_entidad.read()
    
        entidad_service.insert_entidad(nit_entidad, digito_nit, nom_entidad, dir_entidad, tel_entidad, correo_entidad,
                                            pais_entidad, depto_entidad, mun_entidad, cod_habilitacion, gerente, revisor, resolucion_dian, img_data)
        flash("Datos de Entidad agregados exitosamente","success")
        return redirect(url_for('entidad.entidad'))                                 

    except error.Error as e:
        flash(f"Se presentó un erro inesperado: {e.msg}","error")
        return redirect(url_for('entidad.entidad'))
    
    except Exception as ex: 
        flash(f"Se presentó un error inesperado: {ex}","error")
        return redirect(url_for('entidad.entidad'))

#Ruta GET para modificar datos de entidad    
@bp_entidad.get('/edit_entidad/<nit>')
def edit_entidad(nit):
    try:
        et = entidad_service.listar_entidad_nit(nit)
        imagen = BytesIO(et[13])
        if imagen:
            logo = base64.b64encode(imagen.read()).decode('utf-8')

        return render_template('temp_entidad/edit_entidad.html', et = et, logo = logo)

    except error.Error as e: 
        flash(f"Se presentó un error inesperado: {e.msg}","error")
        return redirect(url_for('entidad.entidad'))

    except Exception as ex:
        flash(f"Se presentó un error inesperado: {ex}","error")
        return redirect(url_for('entidad.entidad'))

#Ruta POST para actualizar datos de entidad en base de datos
@bp_entidad.post('/f_updateEntidad')
def f_updateEntidad():
    try:
        nit_entidad = request.form["nit_entidad"]
        digito_nit = request.form["digito_nit"]
        nom_entidad = request.form["nom_entidad"]
        dir_entidad = request.form["dir_entidad"]
        tel_entidad = request.form["tel_entidad"]
        correo_entidad = request.form["correo_entidad"]
        pais_entidad = request.form["pais_entidad"]
        depto_entidad = request.form["depto_entidad"]
        mun_entidad = request.form["mun_entidad"]
        cod_habilitacion = request.form["cod_habilitacion"]
        gerente = request.form["gerente"]
        revisor = request.form["revisor"]
        resolucion_dian = request.form["resolucion_dian"]
        n_entidad = request.form["n_entidad"]
        logo_entidad = request.files["logo_entidad"]
        if logo_entidad:
            img_data = logo_entidad.read()

        entidad_service.update_entidad(nit_entidad, digito_nit, nom_entidad, dir_entidad, tel_entidad, correo_entidad,
                                        pais_entidad, depto_entidad, mun_entidad, cod_habilitacion, gerente, revisor,
                                        resolucion_dian, img_data, n_entidad)
        flash("Datos de Entidad actualizado exitosamente","success")
        return redirect(url_for('entidad.entidad'))

    except error.Error as e:
        flash(f"Se presentó un error inesperado: {e.msg}","error")
        return redirect(url_for('entidad.entidad'))

    except Exception as ex:
        flash(f"Se presentó un error inesperado: {ex}","error")
        return redirect(url_for('entidad.entidad'))


               

app/templates/temp_entidad/add_entidad.html
{% extends 'menu.html' %}

{% block css %}
{% endblock %}
{% block title %}Datos de Entidad{% endblock %}

{% block content %}
<h5 class="title is-5">Datos de Entidad</h5>
<div class="container">
    <form action="{{ url_for('entidad.f_addEntidad') }}" method="post" enctype="multipart/form-data">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">Ingrese la información</p>
            </header>
            <div class="card-content">
                <div class="content">
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field">
                                <div class="field-body">
                                    <div class="field has-addons">
                                        <p class="control">
                                            <label for="nit_entidad" class="label is-small">NIT <strong style="color: red;">*</strong></label>
                                            <input class="input is-small" type="text" name="nit_entidad" id="nit_entidad" required>
                                        </p>
                                        <p class="control">
                                            <label for="digito_nit" class="label is-small">Digito Verf. <strong style="color: red;">*</strong></label>
                                            <input class="input is-small" type="number" name="digito_nit" id="digito_nit" required>
                                        </p>
                                        <p class="control is-expanded">
                                            <label for="nom_entidad" class="label is-small">Razón Social <strong style="color: red;">*</strong></label>
                                            <input class="input is-small" type="text" name="nom_entidad" id="nom_entidad" required>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field">
                                <label for="dir_entidad" class="label is-small">Dirección Ppal. <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="dir_entidad" id="dir_entidad" required>
                            </div>
                            <div class="field">
                                <label for="tel_entidad" class="label is-small">Telefono(s) <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="tel_entidad" id="tel_entidad" required>
                            </div>
                            <div class="field">
                                <label for="correo_entidad" class="label is-small">Correo Electronico <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="email" name="correo_entidad" id="correo_entidad" required>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field">
                                <label for="pais_entidad" class="label is-small">País <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="pais_entidad" id="pais_entidad" required>
                            </div>
                            <div class="field">
                                <label for="depto_entidad" class="label is-small">Departamento <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="depto_entidad" id="depto_entidad" required>
                            </div>
                            <div class="field">
                                <label for="mun_entidad" class="label is-small">Distrito/Municipio <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="mun_entidad" id="mun_entidad" required>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="columns">
                        <div class="column">
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label for="cod_habilitacion" class="label is-small">Codigo Habilitación <strong style="color: red;">*</strong></label>
                                        <input class="input is-small" type="text" name="cod_habilitacion" id="cod_habilitacion" required>
                                    </div>
                                    <div class="field">
                                        <label for="gerente" class="label is-small">Gerente <strong style="color: red;">*</strong></label>
                                        <input class="input is-small" type="text" name="gerente" id="gerente" required>
                                    </div>
                                    <div class="field">
                                        <label for="revisor" class="label is-small">Revisor Fiscal <strong style="color: red;">*</strong></label>
                                        <input class="input is-small" type="text" name="revisor" id="revisor" required>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label for="resolucion_dian" class="label is-small">Resolución DIAN Facturación <strong style="color: red;">*</strong></label>
                                        <p class="control">
                                            <textarea class="textarea is-small" name="resolucion_dian" id="resolucion_dian" required></textarea>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="column">
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label for="logo_entidad" class="label is-small">Logo HC-Reportes <strong style="color: red;">*</strong></label>
                                        <div class="file is-small has-name">
                                            <label class="file-label">
                                            <input class="file-input" type="file" name="logo_entidad" id="logo_entidad" accept="image/*" required/>
                                            <span class="file-cta">
                                                <span class="file-icon"><i class="fa fa-upload"></i></span>
                                                <span class="file-label">Cargar Logo</span>
                                            </span>
                                            <span class="file-name"> Screen Shot 2017-07-29 at 15.54.25.png </span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label class="label is-small">Visualizar Logo</label>
                                        <img id="imgPreview" src="" alt="Vista previa de la imagen" style="max-width: 300px; display: none;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field is-grouped is-grouped-centered">
                    <p class="control">
                        <button class="button is-success">
                            <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/guardar.png') }}" alt="icon"></i></span>
                            <span>Guardar</span>
                        </button>
                    </p>
                    <p class="control">
                        <a onclick="confirmacion()" class="button is-danger">
                            <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/cancelar.png') }}" alt="icon"></i></span>
                            <span>Cancelar</span>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/entidad/entidad.js') }}"></script>
<script>
    const confirmacion = () => {
        Swal.fire({
            title: "Estas Seguro(a)?",
            text: "Los cambios no se guardaran.",
            icon: "question",
            confirmButtonText: "Si, Cancelar!",
            confirmButtonColor: "#48c78e",
            cancelButtonText: "No, Continuar",
            cancelButtonColor: "#f14668",
            showCancelButton: true,
            allowOutsideClick: false
        })
        .then((result) => {
            if(result.isConfirmed){
                window.location.href = "{{ url_for('entidad.entidad') }}"
            }
        })
    }
</script>
{% endblock %}

app/templates/temp_entidad/edit_entidad.html
{% extends 'menu.html' %}

{% block css %}
{% endblock %}
{% block title %}Actualizar Datos de Entidad{% endblock %}

{% block content %}
<h5 class="title is-5">Actualizar Datos de Entidad</h5>
<div class="container">
    <form action="{{ url_for('entidad.f_updateEntidad') }}" method="post" enctype="multipart/form-data">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">Modificar información</p>
            </header>
            <div class="card-content">
                <div class="content">
                    <input type="text" name="n_entidad" id="n_entidad" value="{{ et.0 }}" hidden>
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field">
                                <div class="field-body">
                                    <div class="field has-addons">
                                        <p class="control">
                                            <label for="nit_entidad" class="label is-small">NIT <strong style="color: red;">*</strong></label>
                                            <input class="input is-small" type="text" name="nit_entidad" id="nit_entidad" value="{{ et.0 }}" required>
                                        </p>
                                        <p class="control">
                                            <label for="digito_nit" class="label is-small">Digito Verf. <strong style="color: red;">*</strong></label>
                                            <input class="input is-small" type="number" name="digito_nit" id="digito_nit" value="{{ et.1 }}" required>
                                        </p>
                                        <p class="control is-expanded">
                                            <label for="nom_entidad" class="label is-small">Razón Social <strong style="color: red;">*</strong></label>
                                            <input class="input is-small" type="text" name="nom_entidad" id="nom_entidad" value="{{ et.2 }}" required>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field">
                                <label for="dir_entidad" class="label is-small">Dirección Ppal. <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="dir_entidad" id="dir_entidad" value="{{ et.3 }}" required>
                            </div>
                            <div class="field">
                                <label for="tel_entidad" class="label is-small">Telefono(s) <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="tel_entidad" id="tel_entidad" value="{{ et.4 }}" required>
                            </div>
                            <div class="field">
                                <label for="correo_entidad" class="label is-small">Correo Electronico <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="email" name="correo_entidad" id="correo_entidad" value="{{ et.5 }}" required>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-body">
                            <div class="field">
                                <label for="pais_entidad" class="label is-small">País <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="pais_entidad" id="pais_entidad" value="{{ et.6 }}" required>
                            </div>
                            <div class="field">
                                <label for="depto_entidad" class="label is-small">Departamento <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="depto_entidad" id="depto_entidad" value="{{ et.7 }}" required>
                            </div>
                            <div class="field">
                                <label for="mun_entidad" class="label is-small">Distrito/Municipio <strong style="color: red;">*</strong></label>
                                <input class="input is-small" type="text" name="mun_entidad" id="mun_entidad" value="{{ et.8 }}" required>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="columns">
                        <div class="column">
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label for="cod_habilitacion" class="label is-small">Codigo Habilitación <strong style="color: red;">*</strong></label>
                                        <input class="input is-small" type="text" name="cod_habilitacion" id="cod_habilitacion" value="{{ et.9 }}" required>
                                    </div>
                                    <div class="field">
                                        <label for="gerente" class="label is-small">Gerente <strong style="color: red;">*</strong></label>
                                        <input class="input is-small" type="text" name="gerente" id="gerente" value="{{ et.10 }}" required>
                                    </div>
                                    <div class="field">
                                        <label for="revisor" class="label is-small">Revisor Fiscal <strong style="color: red;">*</strong></label>
                                        <input class="input is-small" type="text" name="revisor" id="revisor" value="{{ et.11 }}" required>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label for="resolucion_dian" class="label is-small">Resolución DIAN Facturación <strong style="color: red;">*</strong></label>
                                        <p class="control">
                                            <textarea class="textarea is-small" name="resolucion_dian" id="resolucion_dian" required>{{ et.12 }}</textarea>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="column">
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label for="logo_entidad" class="label is-small">Logo HC-Reportes <strong style="color: red;">*</strong></label>
                                        <div class="file is-small has-name">
                                            <label class="file-label">
                                            <input class="file-input" type="file" name="logo_entidad" id="logo_entidad" accept="image/*" required/>
                                            <span class="file-cta">
                                                <span class="file-icon"><i class="fa fa-upload"></i></span>
                                                <span class="file-label">Cargar Logo</span>
                                            </span>
                                            <span class="file-name"> Screen Shot 2017-07-29 at 15.54.25.png </span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field is-horizontal">
                                <div class="field-body">
                                    <div class="field">
                                        <label class="label is-small">Visualizar Logo</label>
                                        <img id="imgPreview" src="data:image/png;base64,{{ logo }}" alt="Vista previa de la imagen" style="max-width: 300px; display: block;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field is-grouped is-grouped-centered">
                    <p class="control">
                        <button class="button is-success">
                            <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/actualizar.png') }}" alt="icon"></i></span>
                            <span>Actualizar</span>
                        </button>
                    </p>
                    <p class="control">
                        <a onclick="confirmacion()" class="button is-danger">
                            <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/cancelar.png') }}" alt="icon"></i></span>
                            <span>Cancelar</span>
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/entidad/entidad.js')}}"></script>
<script>
    const confirmacion = () => {
        Swal.fire({
            title: "Estas Seguro(a)?",
            text: "Los cambios no se guardaran.",
            icon: "question",
            confirmButtonText: "Si, Cancelar!",
            confirmButtonColor: "#48c78e",
            cancelButtonText: "No, Continuar",
            cancelButtonColor: "#f14668",
            showCancelButton: true,
            allowOutsideClick: false
        })
        .then((result) => {
            if(result.isConfirmed){
                window.location.href = "{{ url_for('entidad.entidad') }}"
            }
        })
    }
</script>
{% endblock %}

app/templates/temp_entidad/entidad.html
{% extends 'menu.html' %}

{% block css %}
{% endblock %}
{% block title %}Entidad{% endblock %}

{% block content %}
<h5 class="title is-5">Entidad</h5>
<div class="container">
    <div class="field is-grouped">
        <p class="control">
            <a href="{{ url_for('entidad.add_entidad') }}" class="button is-small is-info">
                <span class="icon is-smalll"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/añadir.png')}}" alt="icon"></i></span>
                <span>Datos de Entidad</span>
            </a>
        </p>
    </div>
    <div class="card">
        <header class="card-header">
            <p class="card-header-title">Registros</p>
        </header>
        <div class="card-content">
            <div class="content">
                <table class="table is-striped" style="width: 99%;">
                    <thead>
                        <tr>
                            <th style="width: 33%;" scope="col">NIT</th>
                            <th style="width: 33%;" scope="col">Razón Social</th>
                            <th style="width: 33%;" scope="col">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in ent %}
                        <tr>
                            <td style="width: 33%;">{{ e.nit }}</td>
                            <td style="width: 33%;">{{ e.nombre }}</td>
                            <td style="width: 33%;">
                               <a href="{{ url_for('entidad.edit_entidad', nit = e.nit) }}" class="button is-small is-primary has-tooltip-bottom" data-tooltip="Editar">
                                    <span class="icon is-small"><i><img src="{{ url_for('static', filename='img/icons/editar.png') }}" alt="icon"></i></span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
       {% for category, message in messages %}
       <script>
        document.addEventListener("DOMContentLoaded", () => {
            Swal.fire({
                title: "Notificación!",
                text: "{{ message }}",
                icon: "{{ category }}"
             });
        })
       </script>
       {% endfor %}
    {% endif %}
{% endwith %}

{% endblock %}