app/routes/index_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_bcrypt import Bcrypt
import mysql.connector.errors as error
from app.services import usuario_service

#Nombramos el Blueprint Principal
bp_index = Blueprint('Index', __name__)
bcrypt = Bcrypt()

#Ruta Ventana Pagina Principal Login
@bp_index.get('/')
def index():
    session.clear()
    return render_template('login.html')

#Ruta Metodo Post Recorrido BD usuarios y perfiles y acceso
@bp_index.post('/login_access')
def login_access():
    try:
        usuario = request.form['userId']
        contrasena = request.form['userPass']

        user = usuario_service.listar_usuario_nombre(usuario)
        candidate = user[3]
    
        """ if usuario == '' or contrasena == '':
            flash('Debe diligenciar su usuario y contraseña','warning')
            return render_template('login.html') """
        
        if len(user)>0:
            if bcrypt.check_password_hash(candidate, contrasena):
                session['name'] = user[2]
                session['profile'] = user[4]
                session['document'] = user[0]

                if session['profile'] != 0:
                    return redirect(url_for('Index.dashboard'))
            else:       
                flash('Contraseña Incorrecta', 'warning')
                return render_template('login.html')
        else: 
            flash('Usuario no existe. Contacte al Administrador del Sistema', 'error')
            return render_template('login.html')
        
    except TypeError:
        flash('Usuario no existe. Contacte al Administrador del Sistema', 'error')
        return render_template('login.html')
    
#Ruta Ventana Retorno Pagina Login    
@bp_index.get('/logout')
def logout():
    session.clear()
    return render_template('login.html')

#Ruta Ventana Pagina Principal Dashboard
@bp_index.get('/dashboard')
def dashboard():
    return render_template('dashboard.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block CSS %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
   {% block menu %}
   {% endblock %}

   {% block content %}
   {% endblock %}
</body>

<!-- Scripts -->
{% block scripts %}
{% endblock %}
</html>

app/templates/base_reporte.html
<!DOCTYPE html>
<link rel="stylesheet" href="{{ url_for('static', filename='css/report_style.css') }}">
{% block css %}
{% endblock %}
<title>{% block title %}{% endblock %}</title>
<!-- Encabezado -->
 <table style="height: 100px; width: 639.188px;">
    <tbody>
        <tr>
            <td style="width: 150px;" rowspan="5"><img style="font-size: 14px; float: left; display: block" src="data:image/png;base64,{{ logo }}" alt="vista_previa_logo" width="150" height="64"/></td>
        </tr>
        <tr>
            <td style="width: 20px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: large" colspan="2"><strong>{{ entidad.1 }}</strong></td>
        </tr>
        <tr>
            <td style="width: 20px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: small" colspan="2"><strong>NIT:</strong> {{ entidad.0 }} <strong>Codigo Habilitación:</strong> {{ entidad.5 }}</td>
        </tr>
        <tr>
            <td style="width: 20px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: small" colspan="2"><strong>Dirección:</strong> {{ entidad.2 }} - <strong>Telefonos:</strong> {{ entidad.3 }}</td>
        </tr>
        <tr>
            <td style="width: 20px; text-align: center; font-family: Arial, Helvetica, sans-serif; font-size: small" colspan="2"><strong>Email:</strong><a href="mailto:{{ entidad.4 }}"> {{ entidad.4 }}</a></td>
        </tr>
    </tbody>
</table>
<!-- Contenido -->
{% block report %}
{% endblock %} 


{% block scripts %}
{% endblock %}
</html>

app/templates/dashboard.html
{% extends 'menu.html' %}
{% block title %}Panel Principal{% endblock %}
{% block content %}
<div class="main-container">
    <section class="hero-body">
        <div class="hero-body">
            <p class="title">Bienvenido(a)</p>
            <p class="subtitle">Seleccione una opción del Menú lateral</p>
        </div>
    </section>
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block CSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.min.css') }}">
<!-- <link rel="stylesheet" href="https://jenil.github.io/bulmaswatch/sandstone/bulmaswatch.min.css"> -->
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
<link rel="stylesheet" href="{{ url_for('static', filename='css/sweetalert2.min.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/login-css.css')}}">
{% endblock %}
{% block title %} ClinixOne {% endblock %}

{% block content %}
<div class="columns">
    <div class="column is-two-thirds"></div>
    <div class="column">     
      <div class="container">
        <div class="box login">
          <img class="centrar-imagen" src="{{url_for('static', filename='img/clinixone.webp')}}" alt="logo_clinixone" width="170px" height="110px">
          <!-- <td><img class="centrar-imagen" src="{{url_for('static', filename='assets/logo_empresa.webp')}}" alt="logo_empresa"></td> -->
          <form id="form_login" action="{{ url_for('Index.login_access') }}" method="post">
            <div class="field">
              <p class="control has-icons-left">
                <input class="input" type="text" placeholder="Usuario" name="userId" id="userId">
                <span class="icon is-small is-left">
                  <i class="fa fa-user"></i>
                </span>
              </p>
            </div>
            <div class="field">
              <p class="control has-icons-left">
                <input class="input" type="password" placeholder="Contraseña" name="userPass" id="userPass">
                <span class="icon is-small is-left">
                  <i class="fa fa-lock"></i>
                </span>
              </p>
            </div>
            <div class="field">
              <button class="button is-info is-fullwidth">
                <span class="icon is-small">
                  <i class="fa fa-sign-in"></i>
                </span>
                <span>Iniciar Sesión</span>
              </button>
            </div>
          </form>
          <div class="columns">
            <div class="column is-four-fifths"></div>
            <div class="column">
              <p style="text-align: right;"><strong>v. 1.0.0</strong></p>
            </div>
          </div>
          <div class="columns">
            <div class="column"></div>
            <div class="column">
              <p style="font-size: xx-small; text-align: center;"><strong>Desarrollado por</strong></p>
              <p style="text-align: center;"><img src="{{ url_for('static', filename='img/branding.png')}}" alt="icon-branding" width="80" height="80"></p>
            </div>
            <div class="column"></div>
          </div>
        </div>
      </div>
      <p style="text-align: right;"><a href="https://api.whatsapp.com/send/?phone=573017094993&text=Hola+necesito+soporte&type=phone_number&app_absent=0" target="_blank"><strong>¿Necesita Soporte?</strong></a></p>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <script>
        document.addEventListener('DOMContentLoaded', () =>{
          Swal.fire({
            title: "Notificación!",
            text: "{{ message }}",
            icon: "{{ category }}"
          });
        });
      </script>
    {% endfor %}
  {% endif %}
{% endwith %}

<script src="{{ url_for('static', filename='js/sweetalert2.all.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/login.js') }}"></script>
{% endblock %}